### ISSUE TITLE
``vagrant up`` in the examples directory fails

### ISSUE THREAD

**Issue by jwalgran** [azavea/ansible-beaver#2]
```
[examples]$ vagrant up
 downloading role 'redis', owned by azavea
 - downloading role from https://github.com/azavea/ansible-redis/archive/0.1.0.tar.gz
 - extracting azavea.redis to roles/azavea.redis
azavea.redis was installed successfully
 downloading role 'logstash', owned by azavea
 - downloading role from https://github.com/azavea/ansible-logstash/archive/0.1.0.tar.gz
 - extracting azavea.logstash to roles/azavea.logstash
azavea.logstash was installed successfully
 downloading role 'pip', owned by azavea
 - downloading role from https://github.com/azavea/ansible-pip/archive/0.1.0.tar.gz
 - extracting azavea.pip to roles/azavea.pip
azavea.pip was installed successfully
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: examples_default_1421265799547_50243
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2202 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2202
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/jwalgran/Projects/ansible-beaver/examples
==> default: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [azavea.redis | Install Redis] ****************************************** 
changed: [default]

TASK: [azavea.redis | Configure Redis] **************************************** 
changed: [default]

TASK: [azavea.logstash | Configure Logstash APT key] ************************** 
changed: [default]

TASK: [azavea.logstash | Configure the Logstash APT repositories] ************* 
changed: [default]

TASK: [azavea.logstash | Install Logstash] ************************************ 
changed: [default] => (item=logstash=1.4.2-1-2c0f5a1,logstash-contrib=1.4.2-1-efd53ef)

TASK: [azavea.logstash | Stop Logstash Web service] *************************** 
ok: [default]

TASK: [azavea.logstash | Remove Logstash Web service] ************************* 
changed: [default]

TASK: [azavea.pip | Install pip] ********************************************** 
changed: [default]

TASK: [azavea.beaver | Create service account for Beaver] ********************* 
changed: [default]

TASK: [azavea.beaver | Install Python Docutils] ******************************* 
changed: [default]

TASK: [azavea.beaver | Install Beaver] **************************************** 
failed: [default] => {"cmd": "/usr/bin/pip install beaver==33.0.0", "failed": true, "item": ""}
msg: stdout: Downloading/unpacking beaver==33.0.0
  Running setup.py (path:/tmp/pip_build_root/beaver/setup.py) egg_info for package beaver

Downloading/unpacking boto>=2.8.0 (from beaver==33.0.0)
Downloading/unpacking conf-d>=0.0.4 (from beaver==33.0.0)
  Downloading conf_d-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/conf-d/setup.py) egg_info for package conf-d

Downloading/unpacking glob2==0.3 (from beaver==33.0.0)
  Downloading glob2-0.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/glob2/setup.py) egg_info for package glob2

Downloading/unpacking mosquitto>=1.1 (from beaver==33.0.0)
  Downloading mosquitto-1.2.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/mosquitto/setup.py) egg_info for package mosquitto

Downloading/unpacking msgpack-pure>=0.1.3 (from beaver==33.0.0)
  Downloading msgpack-pure-0.1.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/msgpack-pure/setup.py) egg_info for package msgpack-pure

Downloading/unpacking pika>=0.9.12 (from beaver==33.0.0)
  Running setup.py (path:/tmp/pip_build_root/pika/setup.py) egg_info for package pika

Downloading/unpacking python-daemon>=1.5.2 (from beaver==33.0.0)
  Downloading python_daemon-2.0.3-py2.py3-none-any.whl
Downloading/unpacking redis>=2.7.5 (from beaver==33.0.0)
  Running setup.py (path:/tmp/pip_build_root/redis/setup.py) egg_info for package redis

    warning: no previously-included files found matching '__pycache__'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Downloading/unpacking lockfile>=0.10 (from python-daemon>=1.5.2->beaver==33.0.0)
  Downloading lockfile-0.10.2-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from python-daemon>=1.5.2->beaver==33.0.0)
Requirement already satisfied (use --upgrade to upgrade): docutils in /usr/local/lib/python2.7/dist-packages (from python-daemon>=1.5.2->beaver==33.0.0)
Installing collected packages: beaver, boto, conf-d, glob2, mosquitto, msgpack-pure, pika, python-daemon, redis, lockfile
  Running setup.py install for beaver
    changing mode of build/scripts-2.7/beaver from 644 to 755

    changing mode of /usr/local/bin/beaver to 755
  Running setup.py install for conf-d

  Running setup.py install for glob2

  Running setup.py install for mosquitto

  Running setup.py install for msgpack-pure

  Running setup.py install for pika

  Running setup.py install for redis
    Searching for lockfile>=0.10
    Reading https://pypi.python.org/simple/lockfile/
    Reading http://code.google.com/p/pylockfile/
    Reading http://launchpad.net/pylockfile
    Best match: lockfile 0.10.2
    Downloading https://pypi.python.org/packages/source/l/lockfile/lockfile-0.10.2.tar.gz#md5=1aa6175a6d57f082cd12e7ac6102ab15
    Processing lockfile-0.10.2.tar.gz
    Writing /tmp/easy_install-O4jLbQ/lockfile-0.10.2/setup.cfg
    Running lockfile-0.10.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O4jLbQ/lockfile-0.10.2/egg-dist-tmp-KzJhJl
    Searching for pbr
    Reading https://pypi.python.org/simple/pbr/
    Best match: pbr 0.10.7
    Downloading https://pypi.python.org/packages/source/p/pbr/pbr-0.10.7.tar.gz#md5=3f523231e709ad028497d7af557bf2fb
    Processing pbr-0.10.7.tar.gz
    Writing /tmp/easy_install-O4jLbQ/lockfile-0.10.2/temp/easy_install-XjozEq/pbr-0.10.7/setup.cfg
    Running pbr-0.10.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O4jLbQ/lockfile-0.10.2/temp/easy_install-XjozEq/pbr-0.10.7/egg-dist-tmp-lMZY0R
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/redis/setup.py", line 59, in <module>
        'Programming Language :: Python :: 3.4',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install_egg_info.py", line 46, in run
        self.run_command('egg_info')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 155, in run
        writer = ep.load(installer=installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2087, in load
        if require: self.require(env, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 30, in <module>
        f.close()
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 22, in <module>

      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run
        self.run_command("egg_info")
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 155, in run
        writer = ep.load(installer=installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    ImportError: No module named version
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/redis/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-17iaJF-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/redis

copying redis/sentinel.py -> build/lib.linux-x86_64-2.7/redis

copying redis/client.py -> build/lib.linux-x86_64-2.7/redis

copying redis/utils.py -> build/lib.linux-x86_64-2.7/redis

copying redis/exceptions.py -> build/lib.linux-x86_64-2.7/redis

copying redis/__init__.py -> build/lib.linux-x86_64-2.7/redis

copying redis/_compat.py -> build/lib.linux-x86_64-2.7/redis

copying redis/lock.py -> build/lib.linux-x86_64-2.7/redis

copying redis/connection.py -> build/lib.linux-x86_64-2.7/redis

running install_lib

creating /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/sentinel.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/client.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/utils.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/exceptions.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/__init__.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/_compat.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/lock.py -> /usr/local/lib/python2.7/dist-packages/redis

copying build/lib.linux-x86_64-2.7/redis/connection.py -> /usr/local/lib/python2.7/dist-packages/redis

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/sentinel.py to sentinel.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/client.py to client.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/utils.py to utils.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/exceptions.py to exceptions.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/__init__.py to __init__.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/_compat.py to _compat.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/lock.py to lock.pyc

byte-compiling /usr/local/lib/python2.7/dist-packages/redis/connection.py to connection.pyc

running install_egg_info

running egg_info

Searching for lockfile>=0.10

Reading https://pypi.python.org/simple/lockfile/

Reading http://code.google.com/p/pylockfile/

Reading http://launchpad.net/pylockfile

Best match: lockfile 0.10.2

Downloading https://pypi.python.org/packages/source/l/lockfile/lockfile-0.10.2.tar.gz#md5=1aa6175a6d57f082cd12e7ac6102ab15

Processing lockfile-0.10.2.tar.gz

Writing /tmp/easy_install-O4jLbQ/lockfile-0.10.2/setup.cfg

Running lockfile-0.10.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O4jLbQ/lockfile-0.10.2/egg-dist-tmp-KzJhJl

Searching for pbr

Reading https://pypi.python.org/simple/pbr/

Best match: pbr 0.10.7

Downloading https://pypi.python.org/packages/source/p/pbr/pbr-0.10.7.tar.gz#md5=3f523231e709ad028497d7af557bf2fb

Processing pbr-0.10.7.tar.gz

Writing /tmp/easy_install-O4jLbQ/lockfile-0.10.2/temp/easy_install-XjozEq/pbr-0.10.7/setup.cfg

Running pbr-0.10.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O4jLbQ/lockfile-0.10.2/temp/easy_install-XjozEq/pbr-0.10.7/egg-dist-tmp-lMZY0R

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/redis/setup.py", line 59, in <module>

    'Programming Language :: Python :: 3.4',

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_egg_info.py", line 46, in run

    self.run_command('egg_info')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 155, in run

    writer = ep.load(installer=installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2087, in load

    if require: self.require(env, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require

    working_set.resolve(self.dist.requires(self.extras),env,installer)))

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 30, in <module>

    f.close()

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 22, in <module>



  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run

    self.run_command("egg_info")

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 155, in run

    writer = ep.load(installer=installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load

    entry = __import__(self.module_name, globals(),globals(), ['__name__'])

ImportError: No module named version

----------------------------------------
```

**Comment by jwalgran** [comment]
An upstream problem in python-daemon may be to blame:
https://github.com/azavea/nyc-trees/commit/df519372aa9e72db4867cd3ab0777135492d87ff#commitcomment-9285224
https://lists.alioth.debian.org/pipermail/python-daemon-devel/2015-January/000111.html

**Comment by hectcastro** [comment]
Going to keep an eye on the mailing list for tomorrow. Worst case, we can get around this by making sure that `python-daemon@2.0.2` is installed before installing Beaver.

**Comment by ddohler** [comment]
This appears to break all subsequent attempts to install other modules via pip; I was bit by this this morning: http://stackoverflow.com/questions/27972349/installing-latest-python-daemon-2-0-3-breaks-subsequent-pip-installs

**Comment by hectcastro** [comment]
Attempting to resolve with https://github.com/azavea/ansible-beaver/pull/3.
